### ISSUE TITLE
Perp-Neg in 3D case

### ISSUE THREAD

**Issue by thuliu-yt16** [Perp-Neg/Perp-Neg-stablediffusion#1]
Hi, I am one of the developers of [threestudio](https://github.com/threestudio-project/threestudio). We find this work seems to solve the Janus problem in 3D generation and are now integrating it into our project. 

After carefully reading your paper, we still have several questions about the details. 
1) About the positive and negative prompt set

It is mentioned that the view-dependent prompt is replaced as a set of positive and negative prompts as following
<img width="350" alt="截屏2023-05-18 下午2 00 16" src="https://github.com/Perp-Neg/Perp-Neg-stablediffusion/assets/27289204/1601f47c-cb01-4240-829b-927d7662207a">
So for the front view, the negative prompt set only contains the side-view prompt, so as for the side view.

But later you said that  the positive prompt embedding is an interpolation of the two closest prompt embeddings, such as for  the view between front and side view, the embedding should be
<img width="337" alt="截屏2023-05-18 下午2 02 37" src="https://github.com/Perp-Neg/Perp-Neg-stablediffusion/assets/27289204/b9d92f7a-1999-4b23-ab68-a7968bde5cb2">
The corresponding negative prompt sets should be
<img width="368" alt="截屏2023-05-18 下午2 05 15" src="https://github.com/Perp-Neg/Perp-Neg-stablediffusion/assets/27289204/d1774c88-af85-4b87-88b3-3943741ca052">
Let me suppose that you have the same view division setting as DreamFusion and the azimuth = 0 corresponds to a canonical view. So does it mean for a view with the azimuth degree in [-90, 90], it should be treated as an interpolation between the front and side view? And for the rest, it should be an interpolation between the side and back view? 

Which setting of the above two should I follow?

2) About the weight function of the negative prompts

The negative prompt weights are functions of the interpolation factor r_inter with a form of shifted exponential decay. Could you provide some examples of the function? Currently, we empirically set a=4,b=0.5, and a corresponding c so that f(1) = 0 for all of the four functions but found that the effect is not stable enough. Should these functions be set separately?

**Comment by rezaarmand** [comment]
Thank you so much for reaching out the 3D code is now available @thuliu-yt16 !! thank you so much for the help!
